from typing import Literal

class CoreSession:
    def __init__(self, credential: str, development_root: str | None = None) -> None: ...
    def phase(self, phase_id: Literal["diagnostics", "modules", "plugins", "settings", "window"], message: str) -> None: ...
    def ready(self) -> None: ...
    def failed(self, message: str) -> None: ...
    def check(self) -> None: ...
    def take_activation(self) -> bool: ...
    def take_source_update(self) -> str | None: ...
    def prepare_restart(self) -> str: ...
    def wait_restart(self) -> None: ...
    def cancel_restart(self) -> None: ...
    def close(self) -> None: ...

def update_status() -> tuple[Literal["unavailable"], str]: ...
