from collections.abc import Callable

class DistanceIndex:
    def __init__(self) -> None: ...
    def add(self, value: str, key: int, cancel: Callable[[], None]) -> None: ...
    def query(self, value: str, radius: int, cancel: Callable[[], None]) -> list[tuple[int, int]]: ...

def distances(a: str, jobs: list[tuple[str, int | None]], cancel: Callable[[], None]) -> list[int | None]: ...
def analyze_batch(
    a: str, a_comparison: str, jobs: list[tuple[str, str]], cancel: Callable[[], None],
) -> list[tuple[int, list[tuple[str, int, int, int, int]]]]: ...
