from typing import Literal

def allocate_debug_console() -> tuple[Literal["owned", "attached", "existing", "unavailable"], str]: ...
def configure_desktop_integration(app_id: str) -> None: ...
def is_executable_plugin(path: str) -> bool: ...
def plugin_creation_flags() -> int: ...

class ProcessGroup:
    def __init__(self, pid: int) -> None: ...
    def close(self) -> None: ...
