from typing import Literal

def allocate_debug_console() -> tuple[Literal["owned", "attached", "existing", "unavailable"], str]: ...
def configure_desktop_integration(app_id: str) -> None: ...
def plugin_platform_key() -> str: ...
def executable_name(name: str) -> str: ...
def open_folder(path: str) -> None: ...
def spawn_launcher(command: list[str], environment: dict[str, str]) -> None: ...
def start_plugin(executable: str, args: list[str], cwd: str) -> PluginProcess: ...

class BinaryReader:
    def readline(self, limit: int) -> bytes: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...

class BinaryWriter:
    def write(self, data: bytes) -> int: ...
    def flush(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...

class PluginProcess:
    @property
    def stdin(self) -> BinaryWriter: ...
    @property
    def stdout(self) -> BinaryReader: ...
    @property
    def stderr(self) -> BinaryReader: ...
    def poll(self) -> int | None: ...
    def close(self) -> None: ...
