def configure(settings: str, executable: str, enabled: bool, launcher: list[str], icon: str) -> None: ...
def notifications_available() -> bool: ...
def target_settings(settings: str) -> str: ...
def save_target_settings(settings: str, data: str) -> None: ...
def preview_sound(path: str) -> None: ...
def forget_target(settings: str, project: str) -> None: ...
def running(settings: str) -> bool: ...
def status(settings: str) -> str: ...
def snapshot(settings: str, project: str) -> str: ...
def acknowledge(settings: str, project: str, snapshot: str) -> None: ...
